In [1]:
from transformers import AutoTokenizer, TFBertTokenizer

In [3]:
from transformers import BertModel, BertTokenizer

In [2]:
import torch

In [5]:
model = BertModel.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
sentence = 'I am a MachineLearning Engineer and work in Barcelona'

In [7]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [9]:
tokens = tokenizer.tokenize(sentence)
print(tokens)

['i', 'am', 'a', 'machine', '##lea', '##rn', '##ing', 'engineer', 'and', 'work', 'in', 'barcelona']


In [10]:
tokens = ['[CLS]'] + tokens + ['[SEP]']

In [12]:
print(tokens)

['[CLS]', 'i', 'am', 'a', 'machine', '##lea', '##rn', '##ing', 'engineer', 'and', 'work', 'in', 'barcelona', '[SEP]']


In [13]:
tokens = tokens + ['[PAD]'] + ['[PAD]']
print(tokens)
print(len(tokens))

['[CLS]', 'i', 'am', 'a', 'machine', '##lea', '##rn', '##ing', 'engineer', 'and', 'work', 'in', 'barcelona', '[SEP]', '[PAD]', '[PAD]']
16


In [14]:
attention_mask = [1 if i!= '[PAD]' else 0 for i in tokens]
print(attention_mask)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]


In [15]:
# These tokens represent each word
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print(token_ids)

[101, 1045, 2572, 1037, 3698, 19738, 6826, 2075, 3992, 1998, 2147, 1999, 7623, 102, 0, 0]


In [16]:
# each token has a vector, all tokens vector is the embedding vector

In [17]:
token_ids = torch.tensor(token_ids).unsqueeze(0)
attention_mask = torch.tensor(attention_mask).unsqueeze(0)

In [18]:
output = model(token_ids, attention_mask = attention_mask)

In [21]:
output

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 1.5441e-02,  5.0635e-01, -1.1320e-03,  ..., -3.2490e-01,
           5.9749e-01,  3.5463e-01],
         [ 3.0242e-01,  2.2726e-01, -2.7193e-01,  ...,  4.2097e-04,
           5.2820e-01,  1.5037e-01],
         [ 2.6702e-01,  4.4990e-01,  4.7700e-01,  ..., -5.9956e-01,
           3.5239e-01,  5.3516e-01],
         ...,
         [ 6.0083e-01, -4.7625e-02, -5.3985e-01,  ...,  1.4627e-01,
          -6.9843e-01, -5.1320e-01],
         [-1.0425e-01,  2.8543e-01,  2.1125e-01,  ..., -1.5509e-01,
           7.4580e-01, -1.3839e-01],
         [-2.2645e-01,  1.3089e-01,  1.7929e-01,  ...,  1.7237e-01,
           6.9892e-01, -1.7191e-01]]], grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.8937, -0.6179, -0.9818,  0.8609,  0.8978, -0.2795,  0.8637,  0.4791,
         -0.8812, -1.0000, -0.6820,  0.9861,  0.9729,  0.8106,  0.8969, -0.8738,
         -0.3556, -0.7230,  0.4542, -0.3178,  0.7620,  1.0000, -0.1531,  0.471

In [22]:
# last_hidden_state, hidden representation for each token
# pooler_output, 

In [26]:
output[0].shape

torch.Size([1, 16, 768])

In [28]:
output[1].shape

torch.Size([1, 768])

In [41]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')
print(encoded_input)
output = model(**encoded_input)
print(output)
print(output[0].shape)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


{'input_ids': tensor([[ 101, 5672, 2033, 2011, 2151, 3793, 2017, 1005, 1040, 2066, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.1386,  0.1583, -0.2967,  ..., -0.2708, -0.2844,  0.4581],
         [ 0.5364, -0.2327,  0.1754,  ...,  0.5540,  0.4981, -0.0024],
         [ 0.3002, -0.3475,  0.1208,  ..., -0.4562,  0.3288,  0.8773],
         ...,
         [ 0.3799,  0.1203,  0.8283,  ..., -0.8624, -0.5957,  0.0471],
         [-0.0252, -0.7177, -0.6950,  ...,  0.0757, -0.6668, -0.3401],
         [ 0.7535,  0.2391,  0.0717,  ...,  0.2467, -0.6458, -0.3213]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9377, -0.5043, -0.9799,  0.9030,  0.9329, -0.2438,  0.8926,  0.2288,
         -0.9531, -1.0000, -0.8862,  0.9906,  0.9855,  0.7155,  0.9455, -0.8645,
         -0.6035, -0.6666,  0.3020, -0.1587, 

In [42]:
out = model.generate(**encoded_input,max_length = 24)

TypeError: The current model class (BertModel) is not compatible with `.generate()`, as it doesn't have a language model head. Please use one of the following classes instead: {'BertLMHeadModel'}

In [35]:
prediction_logits = output.prediction_logits
print(prediction_logits)
seq_relationship_logits = output.seq_relationship_logits
print(seq_relationship_logits )

AttributeError: 'BaseModelOutputWithPoolingAndCrossAttentions' object has no attribute 'prediction_logits'

In [31]:
logits = output.logits
logits.shape

AttributeError: 'BaseModelOutputWithPoolingAndCrossAttentions' object has no attribute 'logits'

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [33]:
print(outputs)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.1144,  0.1937,  0.1250,  ..., -0.3827,  0.2107,  0.5407],
         [ 0.5308,  0.3207,  0.3665,  ..., -0.0036,  0.7579,  0.0388],
         [-0.4877,  0.8849,  0.4256,  ..., -0.6976,  0.4458,  0.1231],
         ...,
         [-0.7003, -0.1815,  0.3297,  ..., -0.4838,  0.0680,  0.8901],
         [-1.0355, -0.2567, -0.0317,  ...,  0.3197,  0.3999,  0.1795],
         [ 0.6080,  0.2610, -0.3131,  ...,  0.0311, -0.6283, -0.1994]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-7.1946e-01, -2.1445e-01, -2.9576e-01,  3.6603e-01,  2.7968e-01,
          2.2183e-02,  5.7299e-01,  6.2331e-02,  5.9585e-02, -9.9965e-01,
          5.0145e-02,  4.4756e-01,  9.7612e-01,  3.3989e-02,  8.4494e-01,
         -3.6905e-01,  9.8648e-02, -3.7169e-01,  1.7371e-01,  1.1515e-01,
          4.4133e-01,  9.9525e-01,  3.7221e-01,  8.2881e-02,  2.1402e-01,
          6.8965e-01, -6.1042e-01,  8.7136e-01,  9.4158e-01,  5.737

In [34]:
outputs.last_hidden_state

tensor([[[-0.1144,  0.1937,  0.1250,  ..., -0.3827,  0.2107,  0.5407],
         [ 0.5308,  0.3207,  0.3665,  ..., -0.0036,  0.7579,  0.0388],
         [-0.4877,  0.8849,  0.4256,  ..., -0.6976,  0.4458,  0.1231],
         ...,
         [-0.7003, -0.1815,  0.3297,  ..., -0.4838,  0.0680,  0.8901],
         [-1.0355, -0.2567, -0.0317,  ...,  0.3197,  0.3999,  0.1795],
         [ 0.6080,  0.2610, -0.3131,  ...,  0.0311, -0.6283, -0.1994]]],
       grad_fn=<NativeLayerNormBackward0>)

In [43]:
import torch

from transformers import AutoTokenizer, BertLMHeadModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

model = BertLMHeadModel.from_pretrained("bert-base-uncased")

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")

outputs = model(**inputs, labels=inputs["input_ids"])

loss = outputs.loss

logits = outputs.logits

If you want to use `BertLMHeadModel` as a standalone, add `is_decoder=True.`
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertLMHeadModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertLMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertLMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [44]:
out = model.generate(**inputs,max_length = 24)

In [45]:
print(out)

tensor([[  101,  7592,  1010,  2026,  3899,  2003, 10140,   102,  1012,  1012,
          1012,  1012,  1012,  1012,  1012,  1012,  1012,  1012,  1012,  1012,
          1012,  1012,  1012,  1012]])


In [47]:
tokenizer.decode(out[0])

'[CLS] hello, my dog is cute [SEP]................'

In [60]:
import torch

from transformers import AutoTokenizer, BertLMHeadModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

model = BertLMHeadModel.from_pretrained("bert-base-uncased",return_dict=True, is_decoder = True)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertLMHeadModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertLMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertLMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [61]:
test_sentence = "The Gulf War was a conflict between [MASK]"

In [62]:
tokenized = tokenizer(test_sentence, return_tensors="pt")

outputs = model.generate(**tokenized, max_length=24)

print(outputs)

tensor([[ 101, 1996, 6084, 2162, 2001, 1037, 4736, 2090,  103,  102, 1012, 1012,
         1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012]])


In [63]:
tokenizer.decode(outputs[0])

'[CLS] the gulf war was a conflict between [MASK] [SEP]..............'

In [59]:
from transformers import BertTokenizer, BertLMHeadModel
import torch
from torch.nn import functional as F
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertLMHeadModel.from_pretrained('bert-base-uncased',
return_dict=True, is_decoder = True)
text = "A knife is very [MASK]."
input = tokenizer.encode_plus(text, return_tensors = "pt")
output = model(**input).logits[:, -1, :]
softmax = F.softmax(output, -1)
index = torch.argmax(softmax, dim = -1)
x = tokenizer.decode(index)
print(x)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertLMHeadModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertLMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertLMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


.


In [2]:
from transformers import BertTokenizer, BertForMaskedLM
from torch.nn import functional as F
import torch
tokenizer = BertTokenizer.from_pretrained(pretrained_model_name_or_path= '../bert-base-uncased')
# bert model for masked language modelling
model = BertForMaskedLM.from_pretrained(pretrained_model_name_or_path = '../bert-base-uncased',    return_dict = True)
# return_dict True to use mask token
text = "The capital of Mexico, " + tokenizer.mask_token + ", contains the Mayan piramid."
input = tokenizer.encode_plus(text, return_tensors = "pt")
print(input)
# get index of the mask
mask_index = torch.where(input["input_ids"][0] == tokenizer.mask_token_id)
print(mask_index)
output = model(**input)
# logits are output of BERT model before softmax activation
logits = output.logits
print(logits)
print(logits.shape)

softmax = F.softmax(logits, dim = -1)
print(softmax)
print(softmax.shape)

mask_word = softmax[0, mask_index, :]
top_10 = torch.topk(mask_word, 10, dim = 1)[1][0]
print('top 10 ')

print(top_10)
print('decoded ')

print([tokenizer.decode([token]) for token in top_10])
for token in top_10:
   word = tokenizer.decode([token])
   new_sentence = text.replace(tokenizer.mask_token, word)
   print(new_sentence)

Some weights of the model checkpoint at ../bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


{'input_ids': tensor([[  101,  1996,  3007,  1997,  3290,  1010,   103,  1010,  3397,  1996,
          9815,  2078, 14255,  6444,  3593,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
(tensor([6]),)
tensor([[[ -6.5313,  -6.5047,  -6.5070,  ...,  -5.8149,  -5.6642,  -3.9375],
         [-14.2671, -14.6383, -14.6215,  ..., -13.1567, -11.7743, -13.8698],
         [ -9.7405, -10.3442, -10.0185,  ...,  -9.2343,  -8.1395, -14.4183],
         ...,
         [ -5.2318,  -5.9998,  -5.7009,  ...,  -5.4847,  -6.5367,  -5.8576],
         [-12.6762, -12.1904, -12.8040,  ..., -10.4086, -10.6798,  -7.9790],
         [-14.0402, -14.5983, -14.1129,  ..., -13.5131, -13.5052,  -8.8684]]],
       grad_fn=<ViewBackward0>)
torch.Size([1, 17, 30522])
tensor([[[5.3086e-07, 5.4518e-07, 5.4390e-07,  ..., 1.0867e-06,
          1.2634e-06, 7.1028e-06],
         [4.5584e-16, 3.1449e-16,

In [6]:
a = top_10.add(12)


In [5]:
top_10

tensor([23741, 28631, 22887, 27452, 26923, 28480, 26843,  3290,  9815, 16938])

In [14]:
a = [13420, 22108,  8224,  9980,  7513, 11742,  9733,  6522, 10321, 23853]

In [15]:
"""


The decoded sentence.

Converts a sequence of ids in a string, using the tokenizer and vocabulary with options to remove
special tokens and clean up tokenization spaces.
"""
print([tokenizer.decode([token]) for token in a])


['intel', 'siemens', 'google', 'ibm', 'microsoft', 'toyota', 'amazon', 'hp', 'boeing', 'lego']


In [18]:
tokenizer.convert_ids_to_tokens(a)

['intel',
 'siemens',
 'google',
 'ibm',
 'microsoft',
 'toyota',
 'amazon',
 'hp',
 'boeing',
 'lego']

In [19]:
tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(a))

'intel siemens google ibm microsoft toyota amazon hp boeing lego'